# Use the official docker image.
image: docker:latest
services:
  - docker:dind-rootless

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_DRIVER: overlay2
  IMAGE_PREFIX: git-registry.thm.de/bahn-simulator/libtrainsim

before_script:
  - echo "$K8S_SECRET_DOCKER_ACCESS_TOKEN" | docker login -u "nkrs14" --password-stdin $IMAGE_PREFIX

libtrainsim:ubuntu:
  only:
    - master
  tags:
    - priv
  stage: build
  script:
    - docker build --pull -t "$IMAGE_PREFIX:ubuntu" -f Dockerfile.ubuntu .
    - docker push "$IMAGE_PREFIX:ubuntu"

libtrainsim:fedora:
  only:
    - master
  tags:
    - priv
  stage: build
  script:
    - docker build --pull -t "$IMAGE_PREFIX:fedora" -f Dockerfile.fedora .
    - docker push "$IMAGE_PREFIX:fedora"

libtrainsim:wiki:
  only:
    - master
  tags:
    - priv
  stage: build
  script:
    - docker build --pull -t "$IMAGE_PREFIX:wiki" -f Dockerfile.wiki .
    - docker push "$IMAGE_PREFIX:wiki"

libtrainsim:pages:
  only:
    - master
  tags:
    - priv
  stage: build
  script:
    - docker build --pull -t "$IMAGE_PREFIX:pages" -f Dockerfile.pages .
    - docker push "$IMAGE_PREFIX:pages"
