docker-build:
  # Use the official docker image.
  image: docker:latest
  stage: build
  only:
    - master
  services:
    - name: docker:latest-dind
      alias: docker

  before_script:
    #- echo $K8S_SECRET_DOCKER_ACCESS_TOKEN | docker login -u "noasakurajin" 
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:ubuntu" Dockerfile.ubuntu
    - docker push "$CI_REGISTRY_IMAGE:ubuntu"

