docker-build:
  # Use the official docker image.
  image: docker:latest
  stage: build
  only:
    - master
  tags:
    - priv
  services:
    - docker:dind-rootless

  before_script:
    #- echo $K8S_SECRET_DOCKER_ACCESS_TOKEN | docker login -u "noasakurajin" --password-stdin
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY

  script:
    - docker build -t "libtrainsim:ubuntu" -f Dockerfile.ubuntu .
    - docker push "libtrainsim:ubuntu"

