docker-build:
  # Use the official docker image.
  image: docker:latest
  stage: build
  only:
    - master
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" git.thm.de

  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:ubuntu" Dockerfile.ubuntu
    - docker push "$CI_REGISTRY_IMAGE:ubuntu"

