# Use the official docker image.
image: docker:latest
services:
  - docker:dind-rootless

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_DRIVER: overlay2
  IMAGE_PREFIX: $CI_REGISTRY/bahn-simulator/libtrainsim/image

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY

libtrainsim:ubuntu:
  only:
    - master
  tags:
    - priv
  stage: build
  script:
    - docker build --pull -t "$IMAGE_PREFIX:ubuntu" -f Dockerfile.ubuntu .
    - docker push "$IMAGE_PREFIX:ubuntu"

libtrainsim:fedora:
  only:
    - master
  tags:
    - priv
  stage: build
  script:
    - docker build --pull -t "$IMAGE_PREFIX:fedora" -f Dockerfile.fedora .
    - docker push "$IMAGE_PREFIX:fedora"

libtrainsim:wiki:
  only:
    - master
  tags:
    - priv
  stage: build
  script:
    - docker build --pull -t "$IMAGE_PREFIX:wiki" -f Dockerfile.wiki .
    - docker push "$IMAGE_PREFIX:wiki"

libtrainsim:pages:
  only:
    - master
  tags:
    - priv
  stage: build
  script:
    - docker build --pull -t "$IMAGE_PREFIX:pages" -f Dockerfile.pages .
    - docker push "$IMAGE_PREFIX:pages"
