FROM ubuntu:focal
MAINTAINER Noah Kirschmann <noah.kirschmann@mnd.thm.de>
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -q && apt-get install -qy texlive-full python3-pygments gnuplot make git doxygen graphviz wget unzip make
RUN rm -rf /var/lib/apt/lists/*

WORKDIR /data
VOLUME ["/data"]
